// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcudhsyvfrlfgqqhjrqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdWRoc3l2ZnJsZmdxcWhqcnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjkzMDMsImV4cCI6MjA2NjQwNTMwM30.Ta6FaWtEVw28AwVN06EUT-dBHGgRYribqwdqWK7H49A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);